[package]
name = "mesh_editor"
version = "0.1.0"
edition = "2024"

[[bin]]
name="editor"
path="src/editor/main.rs"

[lib]
path = "src/lib/mod.rs"

[dependencies]
itertools = "0.14.0"
macroquad = "0.4"
strum = { version = "0.26", features = ["derive"] }

[lints.rust]
dead_code = "allow"
