[package]
name = "mesh_editor"
version = "0.1.0"
edition = "2024"

[[bin]]
name="editor"
path="src/editor/main.rs"

[lib]
path = "src/lib/mod.rs"

[dependencies]
macroquad = "0.4"
glam = "0.29"

[lints.rust]
dead_code = "allow"
